import React from 'react';
import { motion } from 'motion/react';

export const Terms: React.FC = () => {
  return (
    <div className="bg-white min-h-screen">
      <section className="py-20 bg-gradient-to-br from-[#ffecd1] to-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.h1
            className="text-4xl sm:text-5xl text-[#001524] mb-6 tracking-tight text-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            Terms of Service
          </motion.h1>
          <motion.p
            className="text-xl text-[#15616d] text-center mb-12"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            Last updated: December 1, 2025
          </motion.p>

          <div className="bg-white border-2 border-[#15616d] rounded-2xl p-8 sm:p-12 shadow-xl space-y-8">
            <div>
              <h2 className="text-2xl text-[#001524] mb-4">1. Acceptance of Terms</h2>
              <p className="text-[#15616d]">
                By accessing or using ContentRex AI ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">2. Description of Service</h2>
              <p className="text-[#15616d] mb-4">
                ContentRex AI provides intelligent content generation and marketing intelligence tools, including AI Content Generator, Content Repurposing tools, Marketing Intelligence suite (YouTube SEO, Trend Hunter, PPC Spy), and SEO analysis.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">3. User Accounts and Registration</h2>
              <p className="text-[#15616d] mb-4">
                To access certain features, you must create an account. You agree to:
              </p>
              <ul className="list-disc list-inside text-[#15616d] space-y-2 ml-4">
                <li>Provide accurate, current, and complete information</li>
                <li>Maintain the security of your account credentials</li>
                <li>Notify us immediately of any unauthorized access</li>
                <li>Be responsible for all activities under your account</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">4. Acceptable Use Policy</h2>
              <p className="text-[#15616d] mb-4">
                You agree NOT to use the Service to:
              </p>
              <ul className="list-disc list-inside text-[#15616d] space-y-2 ml-4">
                <li>Generate content that is illegal, harmful, threatening, or obscene</li>
                <li>Create spam, phishing content, or malicious material</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>Reverse engineer or attempt to extract source code</li>
                <li>Use automated scripts to abuse or overload our systems</li>
                <li>Resell or redistribute the Service without authorization</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">5. Intellectual Property Rights</h2>
              <div className="space-y-4 text-[#15616d]">
                <p>You retain all rights to content you input and content generated by the Service for you. By using the Service, you grant us a limited license to process your content to provide the Service.</p>
                <p>ContentRex AI and its original content, features, and functionality are owned by us and are protected by international copyright, trademark, and other intellectual property laws.</p>
              </div>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">6. Subscription and Payment Terms</h2>
              <p className="text-[#15616d] mb-4">
                Paid features of the Service are subject to the following:
              </p>
              <ul className="list-disc list-inside text-[#15616d] space-y-2 ml-4">
                <li>Subscriptions renew automatically unless cancelled</li>
                <li>Payment is due at the beginning of each billing cycle</li>
                <li>Prices may change with 30 days' notice</li>
                <li>Refunds are provided at our discretion based on our refund policy</li>
                <li>You are responsible for all applicable taxes</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">7. Free Trial and Cancellation</h2>
              <p className="text-[#15616d] mb-4">
                Free trials may be limited to one per user. You may cancel at any time through your account settings. Cancellations take effect at the end of the current billing period.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">8. Refund Policy</h2>
              <p className="text-[#15616d] mb-4">
                We offer refunds within 14 days of your initial purchase or renewal. To request a refund, contact our support team within the 14-day window. Refunds will be processed to your original payment method within 5-10 business days.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">9. Disclaimer of Warranties</h2>
              <p className="text-[#15616d] mb-4">
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING accuracy, reliability, or completeness of AI-generated content, uninterrupted or error-free operation, and merchantability or fitness for a particular purpose.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">10. Limitation of Liability</h2>
              <p className="text-[#15616d]">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, CONTENTREX AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">11. Termination</h2>
              <p className="text-[#15616d] mb-4">
                We may terminate or suspend your account at our sole discretion for conduct that violates these Terms or our policies, is harmful to other users or us, or exposes us to legal liability. Upon termination, your right to use the Service will immediately cease.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">12. Governing Law</h2>
              <p className="text-[#15616d]">
                These Terms are governed by the laws of the State of California, USA. Any disputes shall be resolved through binding arbitration in San Francisco, California, except for claims that may be brought in small claims court.
              </p>
            </div>

            <div>
              <h2 className="text-2xl text-[#001524] mb-4">13. Contact Information</h2>
              <p className="text-[#15616d] mb-4">
                If you have questions about these Terms, please contact us:
              </p>
              <div className="bg-[#ffecd1] rounded-lg p-6">
                <p className="text-[#001524]">
                  <strong>Email:</strong> legal@contentrex.ai<br />
                  <strong>Address:</strong> ContentRex AI Legal Department<br />
                  123 Marketing Street, Suite 100<br />
                  San Francisco, CA 94102, USA
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};