export interface Country {
  name: string;
  code: string;
  locationCode: number;
}

// DataForSEO supported countries (112 countries)
export const countries: Country[] = [
  { name: "Worldwide", code: "WW", locationCode: 2840 },
  { name: "Afghanistan", code: "AF", locationCode: 2004 },
  { name: "Albania", code: "AL", locationCode: 2008 },
  { name: "Algeria", code: "DZ", locationCode: 2012 },
  { name: "Argentina", code: "AR", locationCode: 2032 },
  { name: "Armenia", code: "AM", locationCode: 2051 },
  { name: "Australia", code: "AU", locationCode: 2036 },
  { name: "Austria", code: "AT", locationCode: 2040 },
  { name: "Azerbaijan", code: "AZ", locationCode: 2031 },
  { name: "Bahrain", code: "BH", locationCode: 2048 },
  { name: "Bangladesh", code: "BD", locationCode: 2050 },
  { name: "Belarus", code: "BY", locationCode: 2112 },
  { name: "Belgium", code: "BE", locationCode: 2056 },
  { name: "Bolivia", code: "BO", locationCode: 2068 },
  { name: "Bosnia and Herzegovina", code: "BA", locationCode: 2070 },
  { name: "Brazil", code: "BR", locationCode: 2076 },
  { name: "Bulgaria", code: "BG", locationCode: 2100 },
  { name: "Cambodia", code: "KH", locationCode: 2116 },
  { name: "Canada", code: "CA", locationCode: 2124 },
  { name: "Chile", code: "CL", locationCode: 2152 },
  { name: "Colombia", code: "CO", locationCode: 2170 },
  { name: "Costa Rica", code: "CR", locationCode: 2188 },
  { name: "Croatia", code: "HR", locationCode: 2191 },
  { name: "Cyprus", code: "CY", locationCode: 2196 },
  { name: "Czech Republic", code: "CZ", locationCode: 2203 },
  { name: "Denmark", code: "DK", locationCode: 2208 },
  { name: "Dominican Republic", code: "DO", locationCode: 2214 },
  { name: "Ecuador", code: "EC", locationCode: 2218 },
  { name: "Egypt", code: "EG", locationCode: 2818 },
  { name: "El Salvador", code: "SV", locationCode: 2222 },
  { name: "Estonia", code: "EE", locationCode: 2233 },
  { name: "Ethiopia", code: "ET", locationCode: 2231 },
  { name: "Finland", code: "FI", locationCode: 2246 },
  { name: "France", code: "FR", locationCode: 2250 },
  { name: "Georgia", code: "GE", locationCode: 2268 },
  { name: "Germany", code: "DE", locationCode: 2276 },
  { name: "Ghana", code: "GH", locationCode: 2288 },
  { name: "Greece", code: "GR", locationCode: 2300 },
  { name: "Guatemala", code: "GT", locationCode: 2320 },
  { name: "Honduras", code: "HN", locationCode: 2340 },
  { name: "Hong Kong", code: "HK", locationCode: 2344 },
  { name: "Hungary", code: "HU", locationCode: 2348 },
  { name: "Iceland", code: "IS", locationCode: 2352 },
  { name: "India", code: "IN", locationCode: 2356 },
  { name: "Indonesia", code: "ID", locationCode: 2360 },
  { name: "Iraq", code: "IQ", locationCode: 2368 },
  { name: "Ireland", code: "IE", locationCode: 2372 },
  { name: "Israel", code: "IL", locationCode: 2376 },
  { name: "Italy", code: "IT", locationCode: 2380 },
  { name: "Jamaica", code: "JM", locationCode: 2388 },
  { name: "Japan", code: "JP", locationCode: 2392 },
  { name: "Jordan", code: "JO", locationCode: 2400 },
  { name: "Kazakhstan", code: "KZ", locationCode: 2398 },
  { name: "Kenya", code: "KE", locationCode: 2404 },
  { name: "Kuwait", code: "KW", locationCode: 2414 },
  { name: "Laos", code: "LA", locationCode: 2418 },
  { name: "Latvia", code: "LV", locationCode: 2428 },
  { name: "Lebanon", code: "LB", locationCode: 2422 },
  { name: "Libya", code: "LY", locationCode: 2434 },
  { name: "Lithuania", code: "LT", locationCode: 2440 },
  { name: "Luxembourg", code: "LU", locationCode: 2442 },
  { name: "Malaysia", code: "MY", locationCode: 2458 },
  { name: "Malta", code: "MT", locationCode: 2470 },
  { name: "Mexico", code: "MX", locationCode: 2484 },
  { name: "Moldova", code: "MD", locationCode: 2498 },
  { name: "Mongolia", code: "MN", locationCode: 2496 },
  { name: "Morocco", code: "MA", locationCode: 2504 },
  { name: "Myanmar", code: "MM", locationCode: 2104 },
  { name: "Nepal", code: "NP", locationCode: 2524 },
  { name: "Netherlands", code: "NL", locationCode: 2528 },
  { name: "New Zealand", code: "NZ", locationCode: 2554 },
  { name: "Nicaragua", code: "NI", locationCode: 2558 },
  { name: "Nigeria", code: "NG", locationCode: 2566 },
  { name: "Norway", code: "NO", locationCode: 2578 },
  { name: "Oman", code: "OM", locationCode: 2512 },
  { name: "Pakistan", code: "PK", locationCode: 2586 },
  { name: "Panama", code: "PA", locationCode: 2591 },
  { name: "Paraguay", code: "PY", locationCode: 2600 },
  { name: "Peru", code: "PE", locationCode: 2604 },
  { name: "Philippines", code: "PH", locationCode: 2608 },
  { name: "Poland", code: "PL", locationCode: 2616 },
  { name: "Portugal", code: "PT", locationCode: 2620 },
  { name: "Puerto Rico", code: "PR", locationCode: 2630 },
  { name: "Qatar", code: "QA", locationCode: 2634 },
  { name: "Romania", code: "RO", locationCode: 2642 },
  { name: "Russia", code: "RU", locationCode: 2643 },
  { name: "Saudi Arabia", code: "SA", locationCode: 2682 },
  { name: "Serbia", code: "RS", locationCode: 2688 },
  { name: "Singapore", code: "SG", locationCode: 2702 },
  { name: "Slovakia", code: "SK", locationCode: 2703 },
  { name: "Slovenia", code: "SI", locationCode: 2705 },
  { name: "South Africa", code: "ZA", locationCode: 2710 },
  { name: "South Korea", code: "KR", locationCode: 2410 },
  { name: "Spain", code: "ES", locationCode: 2724 },
  { name: "Sri Lanka", code: "LK", locationCode: 2144 },
  { name: "Sweden", code: "SE", locationCode: 2752 },
  { name: "Switzerland", code: "CH", locationCode: 2756 },
  { name: "Taiwan", code: "TW", locationCode: 2158 },
  { name: "Tanzania", code: "TZ", locationCode: 2834 },
  { name: "Thailand", code: "TH", locationCode: 2764 },
  { name: "Tunisia", code: "TN", locationCode: 2788 },
  { name: "Turkey", code: "TR", locationCode: 2792 },
  { name: "Uganda", code: "UG", locationCode: 2800 },
  { name: "Ukraine", code: "UA", locationCode: 2804 },
  { name: "United Arab Emirates", code: "AE", locationCode: 2784 },
  { name: "United Kingdom", code: "GB", locationCode: 2826 },
  { name: "United States", code: "US", locationCode: 2840 },
  { name: "Uruguay", code: "UY", locationCode: 2858 },
  { name: "Uzbekistan", code: "UZ", locationCode: 2860 },
  { name: "Venezuela", code: "VE", locationCode: 2862 },
  { name: "Vietnam", code: "VN", locationCode: 2704 },
  { name: "Zimbabwe", code: "ZW", locationCode: 2716 }
];
